### PR TITLE
Support for Nuxt

### LINKED ISSUE #48: server-side-render vue
Hi! I have troubles with ssr & vue-medium-editor( 
```
ReferenceError: document is not defined
    at Object.<anonymous> (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:88:22)
    at Object.defineProperty.value (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:7918:30)
    at __webpack_require__ (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:30:30)
    at Object.module.exports (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:7931:21)
    at __webpack_require__ (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:30:30)
    at /node_modules/vue2-medium-editor/dist/vueMediumEditor.js:76:18
    at /node_modules/vue2-medium-editor/dist/vueMediumEditor.js:79:10
    at webpackUniversalModuleDefinition (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:3:20)
    at Object.<anonymous> (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:10:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```
Have you any beta versions with ssr support?

### LINKED ISSUE #61: NuxtJS: window is not defined
I use it with Nuxtjs, config vender and ssr is false but get error: window is not defined. Do you know how to fix this?

### PR DESCRIPTION
**Pull request by trylovetom**
Fix #48 
Fix #61 
support for nuxt, check it's in the browser, if not disable it.

### CODE REVIEW

**Comment by janwirth** [comment]
Hey, thank you for your contribution. Very helpful. Just curious - would it not be cleaner to put the conditional around the entire module? This is kind of messy.

**Review by janwirth — CHANGES_REQUESTED** [review]
Please create a separate file with the conditional that otherwise returns a component that just renders the element.

**Comment by Kirill255** [comment]
Sorry, but can you do something with this PR? Needs the opportunity to use this plugin with SSR?

**Comment by janwirth** [comment]
@Kirill255 will take care soon.

**Comment by janwirth** [comment]
Kirill: try this until then:

https://docs.npmjs.com/cli/install

**Comment by Kirill255** [comment]
@FranzSkuffka I solved my problem three days ago. Don't worry.

**Comment by janwirth** [comment]
@Kirill255 can you share your problem & solution?

**Comment by Kirill255** [comment]
@FranzSkuffka Sure, you can read about my problem above. And you can try to solve it just using this [https://docs.npmjs.com/cli/install](https://docs.npmjs.com/cli/install)

**Comment by trylovetom** [comment]
@FranzSkuffka OK, I will do it.

**Comment by trylovetom** [comment]
@FranzSkuffka Done it

**Comment by janwirth** [comment]
Can you confirm 1.1.16 to work with nuxt?

**Comment by RouillerRomain** [comment]
its working! thanks a lot @trylovetom  !!
(by simply adding the 'Separate File For Nuxt Condition' in the plug-in folder and calling it from a page)

**Comment by janwirth** [comment]
@romain1304 actually with the latest version it should work without any patching..

**Comment by RouillerRomain** [comment]
well i just installed the last version today actually and it didnt work for me,,, may be i did something wrong,,

**Comment by janwirth** [comment]
Thanks for the intel.

**Comment by arihantdaga** [comment]
@FranzSkuffka  I tried the latest version today with nuxt. I am also getting the error - document is not defined. @RouillerRomain  Can you please help me here. I dint understand 

> by simply adding the 'Separate File For Nuxt Condition' in the plug-in folder and calling it from a page

Can you please give a small example, will be very helpful.

**Comment by basselAhmed** [comment]
@arihantdaga try creating a file called **vue2-medium-editor.client.js** in the plugins folder of your nuxt app then including that in your nuxt.config.js
```js
plugins: [
    '~/plugins/vue2-medium-editor.client'
  ]
```
The contents for that file should be standard as so:
```js
import Vue from 'vue'
import editor from 'vue2-medium-editor'

Vue.component('medium-editor', editor)
```

The important bit here is the **.client** in the file name, this tells nuxt to only load this plugin file on the client side where we have the **document** available.

**Comment by arihantdaga** [comment]
@basselAhmed Worked great. But i have a doubt, if we register in the client, will it be loaded globally ?
I want to keep the initial package size to minimum and want to load this component only in one page. 
How can we that ?

**Comment by basselAhmed** [comment]
@arihantdaga Yes it'll be loaded globally, I don't think that will be possible with nuxt unless you set your nuxt mode to **spa** instead of **universal**, that will disable server-side rendering altogether though.

**Comment by arihantdaga** [comment]
Ok.

**Comment by arihantdaga** [comment]
@basselAhmed  I think i found a way. Async Components in vue. 
I used this instead - 
```
import Vue from 'vue'
Vue.component('editor', function (resolve){
         require(['vue2-medium-editor'], resolve)
});

```
And inside my page where i wanted to use editor, simply wrapped it in no-ssr tag.

**Pull request closed without merging**
