### PR TITLE
Fix for "Building for different targets - UMD"

### LINKED ISSUE #8: Building for different targets - UMD
#5 is a request for a browser / ES5 environment version. Does anybody have experience with multi-target builds?

### PR DESCRIPTION
**Pull request by smyth64**
This fixes #8 

I took a lot of inspiration from this project here:
https://github.com/monterail/vue-multiselect

Just added babel as transpiler. Now before pushing to npm just do
```
npm run bulld
```

Running this babel compiles your files in src/ into lib/ make them cross compatible.

Tested it on my machine and this error here became history! #5

### CODE REVIEW

**Comment by smyth64** [comment]
I also added the possibility to provide options for the MediumEditor.

Sorry, didn't notice that I used the 'master' branch for this commit ;)

**Comment by smyth64** [comment]
I also removed the "if" query for the instances. This caused that I could pass options only for one instance but not for the other.

**Comment by janwirth** [comment]
This is great. I will integrate it soon. Thank you very much!

**Comment by janwirth** [comment]
Thank you, I adjusted your changes

**Pull request closed without merging**
