### PR TITLE
Allow watching for changes to editor options

### PR DESCRIPTION
**Pull request by dmattia**
I also removed the ability to reuse a singular root MediumEditor object. There is no function in the MediumEditor API to get all elements under an editor's control, so giving each element its own MediumEditor object simplifies the destruction and recreation necessary for changing an editors options.

See: https://github.com/yabwe/medium-editor/issues/1129

### CODE REVIEW

**Comment by janwirth** [comment]
Sooo I actually like this simplification alot :)
I think the reuse prop was born to cope exactly with this problem, so the simplification is a great thing IMHO.

Notes:
1. As this is a breaking change, we will need a major version bump. Then we should also change the `text` prop to `model`.
2. Do you know if there is any performance impact? There is the `playground` branch that you can use to test that stuff :) How did you proceed during development (just curious).
3. Thank you for thinking of re-rendering dist :) However it would be great to put that in a separate commit (for the future). This keeps the diff more readable!

nice commit :tada:

**Comment by janwirth** [comment]
Bump!

**Comment by dmattia** [comment]
Hello, glad to here your thoughts.  Apologies for the delays, I'm trying to release a library of my own soon and that is taking up a lot of my free time.

I can definitely update the version in the package.json, and I have changed the `text` to `model` locally.

Before I commit though, I am wondering your thoughts on moving the `playground` branch into an `example` directory in the master branch.  The demo is awesome, and having that code easily viewable would be helpful in my opinion (I missed that branch until you mentioned it). This pattern is  becoming *somewhat* popular in other vue component projects such as https://github.com/dmattia/vue-just-another-dropdown

For my testing so far I have actually imported the `index.js` file into a project I am currently working on (repo private unfortunately) and have been testing features on that website.

Lastly, this repo was part of the inspiration for the new project I am working on.  Do I have your permission to use code fragments from this repo in it? I noticed that there is no license currently, so I wanted to ask your permission 👍

**Comment by janwirth** [comment]
Hey, no worries. A lib needs a lot of love to reach the quality for it to be release-ready, so take your time.

- You can of course use my license, but beware that it is _beerware_ 🙂 My software is open source, so just go ahead and take what you need.
- Version bump is good. Add a commit to your PR.
- I have reflected on the `model` approach and was wondering whether it suggests twoway binding. What are your thoughts? vue-medium-editor does not support 2way binding and will not anytime soon. Is it still ok to use `model`?
- Moving the playground branch to examples is a good idea. We will have to add it to the npmignore though.

**Comment by dmattia** [comment]
Is there a reason you don't want to support `v-model`?  If we change the `text`/`model` prop to be called `value` and emit an `input` event instead of a 'edit' event, v-model would work out of the box.

This would also be a breaking change, as instead of using `v-on:edit` on the component, the parent component would use a watcher.  This seems to be a more vue-y way to handle the updates.

If desired, I could add this in to my next commit as well.

What are you thoughts?

**Comment by janwirth** [comment]
`v-model` is incompatible with Vuex. I do not want it to be tho only option.
The problem is that `v-model` mutates the data while `v-on:input` only listens to the latest data update. If we support `v-model` and make it a two-way binding thing we _also_ must support `v-on:input` and `v-bind:value`. If we implement those three interfaces, we are good :)

I would love to do it the most standard way.

**Comment by janwirth** [comment]
Bump! BTW, what do you think with regard to #36 ? I think that it's not really necessary with the change we are working on right now.

**Comment by dmattia** [comment]
Good point on `v-model` and Vuex. I do think having `v-model` support as well as having it emit an input event is ideal, but I will pause on that discussion for now as I think it is too much for this single pull request.  Maybe sometime soon we can talk about it in another thread.

I do think #36 is solved by this, although I'm not sure it needed solving in the first place.  Using data attributes isn't very common from what I've seen in vue.

I will revert back to using `text` for now instead of `model`, and should have the pull request updated with my new request by tomorrow sometime.

**Comment by janwirth** [comment]
Sure! Thank you for this fruitful exchange David! Let's go with `text` for now and then do it as concluded. :)

**Comment by dmattia** [comment]
FranzSkuffka check out the last commit and let me know what you think :)

**Comment by janwirth** [comment]
Just got back from Czech Republic ❤️ 🎧 

Looks great to me. Is this ready to rebase and merge from your POV?

Give me your go and I will do so and publish 1.1.1 🎉

**Comment by dmattia** [comment]
I'd say go!

**Comment by janwirth** [comment]
🤞

**Comment by janwirth** [comment]
I just found out that yarnpkg allows you to bump before publish :)

**Pull request merged**
