### PR TITLE
Passing settings in props

### PR DESCRIPTION
**Pull request by gcoda**
Hey, just added prop for medium editor settings.
Sorry i noob in npm packages, should i run those npm scripts before pull request?

### CODE REVIEW

**Comment by janwirth** [comment]
Thank you very much for the PR.
Glad You made it work for your use case and sharing your efforts.

My suggested approach is to export a function that takes the options and returns the actual component object.

Before you push, please check the coding style using standard js.
https://github.com/feross/standard

**Comment by gcoda** [comment]
I am not really experienced with vue, and only configurable components i have seen were used as plugins registering global elements. it seems like overkill for my personal usecase. 
And it is possible to wrap component props in another component and export editor with configured options.
Anyway, thanks for your work and thank for your time reading this, i just needed to set few options, and props seemed better than hard coding in component source.

**Comment by janwirth** [comment]
@gcoda It's great you requested this feature and sharing your solution with us.

I have an example implementation in mind already that allows multiple configurations without cluttering the DOM.

Will keep you posted & wish you all the fun developing.

**Comment by janwirth** [comment]
I used your code, created a PR which is yet to test and added you to the contributor list :)

**Pull request closed without merging**
