### PR TITLE
Add MediumEditor reference to the component for external use

### PR DESCRIPTION
**Pull request by pizzot**
I have tried to add a custom button and could not find a way to get access to MediumEditor itself. Sorted the issue by adding the reference to the VueMediumEditor object.

Just sharing my solution, let me know if there is a better way to reslve this.

### CODE REVIEW

**Comment by janwirth** [comment]
Thank you for your contribution.

I like this solution. Good job. Can you explain what happens for either `true` or `false` in the `reuseMediumEditorInstance` prop? This must be compatible. If it is, i will not hesitate to merge :)

Right now I am working on fixing up all the issues, want to publish a new version tonight, but I am running into major issues with regard to the `customElement` option.

**Comment by pizzot** [comment]
This is the the reference to the MediumEditor class, not the particular instance, should cause no issues.

**Comment by janwirth** [comment]
Thank you very much. I will push a compiled version for you in a few minutes so that you can use the latest one :)

**Comment by pizzot** [comment]
Great, thanks :)

**Comment by janwirth** [comment]
You should now be able to install the latest version using
```npm i -S franzskuffka/vue-medium-editor#1b23b3e2ea6d9cb46984bf5d9ac2b294f116d04e```

**Please let me know if it works for you now.**

**Comment by pizzot** [comment]
Yeah, all works now :)

Thanks

**Pull request merged**
